export const customStyles = {
  control: (styles, { isFocused }) => ({
    ...styles,
    width: "100%",
    maxWidth: "14rem",
    minWidth: "12rem",
    borderRadius: "10px",
    color: "#000",
    fontSize: "0.9rem",
    lineHeight: "1.75rem",
    backgroundColor: "#FFFFFF",
    cursor: "pointer",
    border: isFocused ? "2px solid #007BFF" : "2px solid #CCCCCC",
    boxShadow: isFocused ? "0 0 10px rgba(0, 123, 255, 0.5)" : "0 0 5px rgba(0, 0, 0, 0.1)",
    transition: "all 0.3s ease",
    ":hover": {
      border: "2px solid #007BFF",
      boxShadow: "0 0 10px rgba(0, 123, 255, 0.5)",
    },
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
  option: (styles, { isFocused, isSelected }) => ({
    ...styles,
    color: isSelected ? "#FFFFFF" : "#000",
    backgroundColor: isSelected ? "#007BFF" : isFocused ? "rgba(0, 123, 255, 0.1)" : "#FFF",
    fontSize: "0.9rem",
    lineHeight: "1.75rem",
    width: "100%",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    cursor: "pointer",
    transition: "all 0.3s ease",
    ":hover": {
      backgroundColor: "rgba(0, 123, 255, 0.2)",
      color: "#000",
    },
  }),
  menu: (styles) => ({
    ...styles,
    backgroundColor: "#FFF",
    maxWidth: "14rem",
    border: "2px solid #CCCCCC",
    borderRadius: "10px",
    boxShadow: "0 5px 15px rgba(0, 0, 0, 0.1)",
    transition: "all 0.3s ease",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
  placeholder: (defaultStyles) => ({
    ...defaultStyles,
    color: "#AAAAAA",
    fontSize: "0.9rem",
    lineHeight: "1.75rem",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
  singleValue: (defaultStyles) => ({
    ...defaultStyles,
    color: "#000",
    fontSize: "0.9rem",
    lineHeight: "1.75rem",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
  input: (defaultStyles) => ({
    ...defaultStyles,
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
};
